name: pdfscanner
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.1
  google_ml_kit: ^0.13.0
  # google_mlkit_text_recognition: ^0.5.0
  image_picker: ^0.8.6+1
  clipboard: ^0.1.3


  flutter_native_splash: ^2.2.17


  
flutter_native_splash:
  color : "#0063dd"
  image: assets/logo.png
  android: true
  ios: true


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
